--------------------------------------------------------
--  File created - Sunday-March-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "COUNTRIES" ("ID" NUMBER(11,0), "SORTNAME" VARCHAR2(3), "NAME" VARCHAR2(150), "PHONECODE" NUMBER(11,0))
REM INSERTING into COUNTRIES
SET DEFINE OFF;
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (1,'AF','Afghanistan',93);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (2,'AL','Albania',355);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (3,'DZ','Algeria',213);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (4,'AS','American Samoa',1684);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (5,'AD','Andorra',376);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (6,'AO','Angola',244);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (7,'AI','Anguilla',1264);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (8,'AQ','Antarctica',0);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (9,'AG','Antigua And Barbuda',1268);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (10,'AR','Argentina',54);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (11,'AM','Armenia',374);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (12,'AW','Aruba',297);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (13,'AU','Australia',61);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (14,'AT','Austria',43);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (15,'AZ','Azerbaijan',994);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (16,'BS','Bahamas The',1242);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (17,'BH','Bahrain',973);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (18,'BD','Bangladesh',880);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (19,'BB','Barbados',1246);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (20,'BY','Belarus',375);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (21,'BE','Belgium',32);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (22,'BZ','Belize',501);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (23,'BJ','Benin',229);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (24,'BM','Bermuda',1441);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (25,'BT','Bhutan',975);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (26,'BO','Bolivia',591);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (27,'BA','Bosnia and Herzegovina',387);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (28,'BW','Botswana',267);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (29,'BV','Bouvet Island',0);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (30,'BR','Brazil',55);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (31,'IO','British Indian Ocean Territory',246);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (32,'BN','Brunei',673);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (33,'BG','Bulgaria',359);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (34,'BF','Burkina Faso',226);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (35,'BI','Burundi',257);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (36,'KH','Cambodia',855);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (37,'CM','Cameroon',237);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (38,'CA','Canada',1);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (39,'CV','Cape Verde',238);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (40,'KY','Cayman Islands',1345);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (41,'CF','Central African Republic',236);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (42,'TD','Chad',235);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (43,'CL','Chile',56);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (44,'CN','China',86);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (45,'CX','Christmas Island',61);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (46,'CC','Cocos(Keeling) Islands',672);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (47,'CO','Colombia',57);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (48,'KM','Comoros',269);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (49,'CG','Republic Of The Congo',242);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (50,'CD','Democratic Republic Of The Congo',242);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (51,'CK','Cook Islands',682);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (52,'CR','Costa Rica',506);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (53,'CI','Cote D''Ivoire (Ivory Coast)',225);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (54,'HR','Croatia  (Hrvatska)',385);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (55,'CU','Cuba',53);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (56,'CY','Cyprus',357);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (57,'CZ','Czech Republic',420);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (58,'DK','Denmark',45);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (59,'DJ','Djibouti',253);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (60,'DM','Dominica',1767);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (61,'DO','Dominican Republic',1809);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (62,'TP','East Timor',670);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (63,'EC','Ecuador',593);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (64,'EG','Egypt',20);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (65,'SV','El Salvador',503);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (66,'GQ','Equatorial Guinea',240);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (67,'ER','Eritrea',291);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (68,'EE','Estonia',372);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (69,'ET','Ethiopia',251);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (70,'XA','External Territories of Australia',61);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (71,'FK','Falkland Islands',500);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (72,'FO','Faroe Islands',298);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (73,'FJ','Fiji Islands',679);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (74,'FI','Finland',358);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (75,'FR','France',33);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (76,'GF','French Guiana',594);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (77,'PF','French Polynesia',689);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (78,'TF','French Southern Territories',0);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (79,'GA','Gabon',241);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (80,'GM','Gambia The',220);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (81,'GE','Georgia',995);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (82,'DE','Germany',49);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (83,'GH','Ghana',233);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (84,'GI','Gibraltar',350);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (85,'GR','Greece',30);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (86,'GL','Greenland',299);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (87,'GD','Grenada',1473);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (88,'GP','Guadeloupe',590);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (89,'GU','Guam',1671);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (90,'GT','Guatemala',502);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (91,'XU','Guernsey and Alderney',44);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (92,'GN','Guinea',224);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (93,'GW','Guinea-Bissau',245);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (94,'GY','Guyana',592);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (95,'HT','Haiti',509);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (96,'HM','Heard and McDonald Islands',0);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (97,'HN','Honduras',504);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (98,'HK','Hong Kong S.A.R.',852);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (99,'HU','Hungary',36);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (100,'IS','Iceland',354);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (101,'IN','India',91);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (102,'ID','Indonesia',62);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (103,'IR','Iran',98);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (104,'IQ','Iraq',964);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (105,'IE','Ireland',353);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (106,'IL','Israel',972);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (107,'IT','Italy',39);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (108,'JM','Jamaica',1876);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (109,'JP','Japan',81);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (110,'XJ','Jersey',44);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (111,'JO','Jordan',962);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (112,'KZ','Kazakhstan',7);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (113,'KE','Kenya',254);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (114,'KI','Kiribati',686);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (115,'KP','Korea North',850);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (116,'KR','Korea South',82);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (117,'KW','Kuwait',965);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (118,'KG','Kyrgyzstan',996);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (119,'LA','Laos',856);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (120,'LV','Latvia',371);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (121,'LB','Lebanon',961);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (122,'LS','Lesotho',266);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (123,'LR','Liberia',231);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (124,'LY','Libya',218);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (125,'LI','Liechtenstein',423);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (126,'LT','Lithuania',370);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (127,'LU','Luxembourg',352);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (128,'MO','Macau S.A.R.',853);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (129,'MK','Macedonia',389);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (130,'MG','Madagascar',261);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (131,'MW','Malawi',265);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (132,'MY','Malaysia',60);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (133,'MV','Maldives',960);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (134,'ML','Mali',223);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (135,'MT','Malta',356);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (136,'XM','Man (Isle of)',44);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (137,'MH','Marshall Islands',692);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (138,'MQ','Martinique',596);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (139,'MR','Mauritania',222);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (140,'MU','Mauritius',230);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (141,'YT','Mayotte',269);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (142,'MX','Mexico',52);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (143,'FM','Micronesia',691);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (144,'MD','Moldova',373);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (145,'MC','Monaco',377);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (146,'MN','Mongolia',976);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (147,'MS','Montserrat',1664);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (148,'MA','Morocco',212);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (149,'MZ','Mozambique',258);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (150,'MM','Myanmar',95);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (151,'NA','Namibia',264);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (152,'NR','Nauru',674);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (153,'NP','Nepal',977);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (154,'AN','Netherlands Antilles',599);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (155,'NL','Netherlands The',31);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (156,'NC','New Caledonia',687);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (157,'NZ','New Zealand',64);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (158,'NI','Nicaragua',505);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (159,'NE','Niger',227);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (160,'NG','Nigeria',234);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (161,'NU','Niue',683);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (162,'NF','Norfolk Island',672);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (163,'MP','Northern Mariana Islands',1670);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (164,'NO','Norway',47);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (165,'OM','Oman',968);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (166,'PK','Pakistan',92);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (167,'PW','Palau',680);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (168,'PS','Palestinian Territory Occupied',970);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (169,'PA','Panama',507);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (170,'PG','Papua new Guinea',675);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (171,'PY','Paraguay',595);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (172,'PE','Peru',51);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (173,'PH','Philippines',63);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (174,'PN','Pitcairn Island',0);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (175,'PL','Poland',48);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (176,'PT','Portugal',351);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (177,'PR','Puerto Rico',1787);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (178,'QA','Qatar',974);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (179,'RE','Reunion',262);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (180,'RO','Romania',40);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (181,'RU','Russia',70);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (182,'RW','Rwanda',250);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (183,'SH','Saint Helena',290);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (184,'KN','Saint Kitts And Nevis',1869);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (185,'LC','Saint Lucia',1758);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (186,'PM','Saint Pierre and Miquelon',508);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (187,'VC','Saint Vincent And The Grenadines',1784);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (188,'WS','Samoa',684);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (189,'SM','San Marino',378);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (190,'ST','Sao Tome and Principe',239);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (191,'SA','Saudi Arabia',966);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (192,'SN','Senegal',221);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (193,'RS','Serbia',381);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (194,'SC','Seychelles',248);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (195,'SL','Sierra Leone',232);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (196,'SG','Singapore',65);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (197,'SK','Slovakia',421);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (198,'SI','Slovenia',386);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (199,'XG','Smaller Territories of the UK',44);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (200,'SB','Solomon Islands',677);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (201,'SO','Somalia',252);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (202,'ZA','South Africa',27);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (203,'GS','South Georgia',0);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (204,'SS','South Sudan',211);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (205,'ES','Spain',34);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (206,'LK','Sri Lanka',94);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (207,'SD','Sudan',249);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (208,'SR','Suriname',597);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (209,'SJ','Svalbard And Jan Mayen Islands',47);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (210,'SZ','Swaziland',268);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (211,'SE','Sweden',46);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (212,'CH','Switzerland',41);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (213,'SY','Syria',963);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (214,'TW','Taiwan',886);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (215,'TJ','Tajikistan',992);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (216,'TZ','Tanzania',255);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (217,'TH','Thailand',66);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (218,'TG','Togo',228);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (219,'TK','Tokelau',690);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (220,'TO','Tonga',676);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (221,'TT','Trinidad And Tobago',1868);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (222,'TN','Tunisia',216);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (223,'TR','Turkey',90);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (224,'TM','Turkmenistan',7370);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (225,'TC','Turks And Caicos Islands',1649);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (226,'TV','Tuvalu',688);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (227,'UG','Uganda',256);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (228,'UA','Ukraine',380);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (229,'AE','United Arab Emirates',971);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (230,'GB','United Kingdom',44);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (231,'US','United States',1);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (232,'UM','United States Minor Outlying Islands',1);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (233,'UY','Uruguay',598);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (234,'UZ','Uzbekistan',998);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (235,'VU','Vanuatu',678);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (236,'VA','Vatican City State(Holy See)',39);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (237,'VE','Venezuela',58);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (238,'VN','Vietnam',84);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (239,'VG','Virgin Islands (British)',1284);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (240,'VI','Virgin Islands (US)',1340);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (241,'WF','Wallis And Futuna Islands',681);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (242,'EH','Western Sahara',212);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (243,'YE','Yemen',967);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (244,'YU','Yugoslavia',38);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (245,'ZM','Zambia',260);
Insert into COUNTRIES (ID,SORTNAME,NAME,PHONECODE) values (246,'ZW','Zimbabwe',263);
--------------------------------------------------------
--  DDL for Index SYS_C007317
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007317" ON "COUNTRIES" ("ID")
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "COUNTRIES" MODIFY ("ID" NOT NULL ENABLE)
  ALTER TABLE "COUNTRIES" MODIFY ("SORTNAME" NOT NULL ENABLE)
  ALTER TABLE "COUNTRIES" MODIFY ("NAME" NOT NULL ENABLE)
  ALTER TABLE "COUNTRIES" MODIFY ("PHONECODE" NOT NULL ENABLE)
  ALTER TABLE "COUNTRIES" ADD PRIMARY KEY ("ID") ENABLE
