--------------------------------------------------------
--  File created - Sunday-March-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "PAYMENT" ("CC_NUMBER" VARCHAR2(45), "CC_NAME" VARCHAR2(45), "CC_CVV" NUMBER(3,0), "CC_EXPIRY_MONTH" NUMBER(2,0), "CC_EXPIRY_YEAR" NUMBER(4,0), "CUSTOMER_ID" NUMBER(10,0))
REM INSERTING into PAYMENT
SET DEFINE OFF;
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('39745823158','RAVI TEJA',147,2,17,1);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',125,12,12,604);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',125,12,12,604);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',125,12,12,1);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',123,12,12,604);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('1258963','sai',125,12,12,602);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',233,12,12,604);
Insert into PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('98745632198745','ram',123,12,34,604);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "PAYMENT" MODIFY ("CC_NUMBER" NOT NULL ENABLE)
  ALTER TABLE "PAYMENT" MODIFY ("CC_NAME" NOT NULL ENABLE)
  ALTER TABLE "PAYMENT" MODIFY ("CC_CVV" NOT NULL ENABLE)
  ALTER TABLE "PAYMENT" MODIFY ("CC_EXPIRY_MONTH" NOT NULL ENABLE)
  ALTER TABLE "PAYMENT" MODIFY ("CC_EXPIRY_YEAR" NOT NULL ENABLE)
  ALTER TABLE "PAYMENT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE)
