--------------------------------------------------------
--  File created - Sunday-March-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "SUBCATEGORY" ("SUBCATEGORY_ID" NUMBER(10,0), "CATEGORY_ID" NUMBER(10,0), "NAME" VARCHAR2(45), "DESCRIPTION" VARCHAR2(200))
REM INSERTING into SUBCATEGORY
SET DEFINE OFF;
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000100,1000125,'Apple',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000101,1000125,'Motorola',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000102,1000126,'Novels',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000103,1000126,'Literature',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000104,1000126,'Academics',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000105,1000126,'Biography',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000106,1000125,'Blackberry',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000107,1000127,'Action',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000108,1000127,'Comedy',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000109,1000127,'Thriller',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000110,1000127,'Sci-Fi',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000111,1000128,'Arcade',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000112,1000128,'Sports',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000113,1000128,'RPG',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000114,1000128,'Adventure',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000115,1000125,'Sony',null);
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000116,1000129,'Top wear','Shirts');
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000117,1000129,'bottom wear','shirts and pants');
Insert into SUBCATEGORY (SUBCATEGORY_ID,CATEGORY_ID,NAME,DESCRIPTION) values (1000118,1000130,'Kitchen &Dining',null);
--------------------------------------------------------
--  DDL for Index PK_SUBID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SUBID" ON "SUBCATEGORY" ("SUBCATEGORY_ID")
--------------------------------------------------------
--  Constraints for Table SUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "SUBCATEGORY" MODIFY ("SUBCATEGORY_ID" NOT NULL ENABLE)
  ALTER TABLE "SUBCATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE)
  ALTER TABLE "SUBCATEGORY" MODIFY ("NAME" NOT NULL ENABLE)
  ALTER TABLE "SUBCATEGORY" ADD CONSTRAINT "PK_SUBID" PRIMARY KEY ("SUBCATEGORY_ID") ENABLE
