--------------------------------------------------------
--  File created - Sunday-February-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERACTIVATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMERACTIVATION" 
   (	"TOKEN" VARCHAR2(255 BYTE), 
	"EXPIRY_DATE" TIMESTAMP (6), 
	"CUSTOMER_ID" NUMBER(11,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMERACTIVATION
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table CUSTOMERACTIVATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMERACTIVATION" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMERACTIVATION" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMERACTIVATION" MODIFY ("TOKEN" NOT NULL ENABLE);
