--------------------------------------------------------
--  File created - Monday-February-05-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PAYMENT" 
   (	"CC_NUMBER" VARCHAR2(45 BYTE), 
	"CC_NAME" VARCHAR2(45 BYTE), 
	"CC_CVV" NUMBER(3,0), 
	"CC_EXPIRY_MONTH" NUMBER(2,0), 
	"CC_EXPIRY_YEAR" NUMBER(4,0), 
	"CUSTOMER_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PAYMENT
SET DEFINE OFF;
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('39745823158','RAVI TEJA',147,2,17,1);
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',125,12,12,604);
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',125,12,12,604);
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',125,12,12,1);
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',123,12,12,604);
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('1258963','sai',125,12,12,602);
Insert into SYSTEM.PAYMENT (CC_NUMBER,CC_NAME,CC_CVV,CC_EXPIRY_MONTH,CC_EXPIRY_YEAR,CUSTOMER_ID) values ('12552565265','ram',233,12,12,604);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("CC_EXPIRY_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("CC_EXPIRY_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("CC_CVV" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("CC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("CC_NUMBER" NOT NULL ENABLE);
