--------------------------------------------------------
--  File created - Monday-February-05-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADDRESS" 
   (	"ADDRESS_ID" NUMBER(10,0), 
	"FULLNAME" VARCHAR2(45 BYTE), 
	"ADDRESS_1" VARCHAR2(200 BYTE), 
	"ADDRESS_2" VARCHAR2(45 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"ZIP" VARCHAR2(45 BYTE), 
	"STATE" VARCHAR2(45 BYTE), 
	"CUSTOMER_ID" NUMBER(10,0), 
	"COUNTRY" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADDRESS
SET DEFINE OFF;
Insert into SYSTEM.ADDRESS (ADDRESS_ID,FULLNAME,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,CUSTOMER_ID,COUNTRY) values (384735,'Ravi Teja','SR Nagar','SR nagar','hyd','500038','TS',1,'India');
Insert into SYSTEM.ADDRESS (ADDRESS_ID,FULLNAME,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,CUSTOMER_ID,COUNTRY) values (671094,'Jagadeesh','Mgh-35,Ameerpet','Sathyam hall','Addanki','500037','Andhra Pradesh',4,'India');
Insert into SYSTEM.ADDRESS (ADDRESS_ID,FULLNAME,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,CUSTOMER_ID,COUNTRY) values (125460126,'ram','4-54/1,Athota','nadhiveylugu','Belampalli','522307','Andhra Pradesh',604,'India');
Insert into SYSTEM.ADDRESS (ADDRESS_ID,FULLNAME,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,CUSTOMER_ID,COUNTRY) values (73384921,'teja','4-54,Athota','nadhiveylugu','Tenali','522306','Andhra Pradesh',601,'India');
--------------------------------------------------------
--  DDL for Index PK_ADDRESSID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ADDRESSID" ON "SYSTEM"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" ADD CONSTRAINT "PK_ADDRESSID" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("ADDRESS_2" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("ADDRESS_1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
