--------------------------------------------------------
--  File created - Monday-February-05-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMERADDRESS" 
   (	"CUSTOMERADDRESS_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"ADDRESS_ID" NUMBER(10,0), 
	"CUSTOMER_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMERADDRESS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CUSTOMERADDRESSID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CUSTOMERADDRESSID" ON "SYSTEM"."CUSTOMERADDRESS" ("CUSTOMERADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMERADDRESS" ADD CONSTRAINT "PK_CUSTOMERADDRESSID" PRIMARY KEY ("CUSTOMERADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMERADDRESS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMERADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMERADDRESS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMERADDRESS" MODIFY ("CUSTOMERADDRESS_ID" NOT NULL ENABLE);
