--------------------------------------------------------
--  File created - Monday-February-05-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SHIPPINGADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SHIPPINGADDRESS" 
   (	"SHIPPING_ID" NUMBER(10,0), 
	"ADDRESS_1" VARCHAR2(200 BYTE), 
	"ADDRESS_2" VARCHAR2(45 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"ZIP" VARCHAR2(45 BYTE), 
	"STATE" VARCHAR2(45 BYTE), 
	"FULLNAME" VARCHAR2(45 BYTE), 
	"CUSTOMER_ID" NUMBER(10,0), 
	"COUNTRY" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SHIPPINGADDRESS
SET DEFINE OFF;
Insert into SYSTEM.SHIPPINGADDRESS (SHIPPING_ID,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,FULLNAME,CUSTOMER_ID,COUNTRY) values (368249,'SR Nagar','SR nagar','hyd','500038','TS','Ravi Teja',1,'India');
Insert into SYSTEM.SHIPPINGADDRESS (SHIPPING_ID,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,FULLNAME,CUSTOMER_ID,COUNTRY) values (1784995,'Mgh-35,Ameerpet','Sathyam hall','Addanki','500037','Andhra Pradesh','Jagadeesh',4,'India');
Insert into SYSTEM.SHIPPINGADDRESS (SHIPPING_ID,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,FULLNAME,CUSTOMER_ID,COUNTRY) values (211647978,'4-50,Athota','nadhiveylugu','Tenali','522306','Andhra Pradesh','ram',604,'India');
Insert into SYSTEM.SHIPPINGADDRESS (SHIPPING_ID,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,FULLNAME,CUSTOMER_ID,COUNTRY) values (338326,'SR Nagar phase-1','SR nagar','hyd','500038','TS','Ravi Teja',1,'India');
Insert into SYSTEM.SHIPPINGADDRESS (SHIPPING_ID,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,FULLNAME,CUSTOMER_ID,COUNTRY) values (165037943,'4-54,Athota','nadhiveylugu','Tenali','522306','Andhra Pradesh','sai',602,'India');
Insert into SYSTEM.SHIPPINGADDRESS (SHIPPING_ID,ADDRESS_1,ADDRESS_2,CITY,ZIP,STATE,FULLNAME,CUSTOMER_ID,COUNTRY) values (290560413,'4-54,Athota','nadhiveylugu','Tenali','522306','Andhra Pradesh','ram',604,'India');
--------------------------------------------------------
--  DDL for Index PK_SHIPPINGID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_SHIPPINGID" ON "SYSTEM"."SHIPPINGADDRESS" ("SHIPPING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SHIPPINGADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" ADD CONSTRAINT "PK_SHIPPINGID" PRIMARY KEY ("SHIPPING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("ADDRESS_2" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("ADDRESS_1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHIPPINGADDRESS" MODIFY ("SHIPPING_ID" NOT NULL ENABLE);
